/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "klqquksrfldaxjwyimzy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscXF1a3NyZmxkYXhqd3lpbXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4OTI3NzYsImV4cCI6MjA4NjQ2ODc3Nn0.nbWnWNDN-CHtCZjsXtAG5Mp0LL-rDMqRW8rXvBpsTK0"